spring:
  application:
    name: admin-feign
  zipkin:
    base-url: http://localhost:9411
server:
  port: 8086
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8081/eureka/


feign:
  hystrix:
    enabled: true
